"""init schema

Revision ID: 7cd9ccf59c1f
Revises: 
Create Date: 2025-09-09 22:13:41.321714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd9ccf59c1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lk_companies',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_image_url', sa.TEXT(), nullable=True),
    sa.Column('company_description', sa.TEXT(), nullable=True),
    sa.Column('company_staff_count', sa.Integer(), nullable=True),
    sa.Column('company_url', sa.String(length=1000), nullable=True),
    sa.Column('company_follower_count', sa.String(length=255), nullable=True),
    sa.Column('company_industries', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('lk_etl_status',
    sa.Column('etl_id', sa.Integer(), nullable=False),
    sa.Column('etl_search', sa.String(length=255), nullable=True),
    sa.Column('etl_url', sa.String(length=2000), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('etl_id')
    )
    op.create_table('lk_jobs',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('job_name', sa.String(length=1000), nullable=True),
    sa.Column('standardized_name', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=True),
    sa.Column('job_description', sa.TEXT(), nullable=True),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('job_min_salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('job_max_salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('job_pay_period', sa.String(length=255), nullable=True),
    sa.Column('job_functions', sa.TEXT(), nullable=True),
    sa.Column('job_experience_level', sa.String(length=255), nullable=True),
    sa.Column('job_views', sa.Integer(), nullable=True),
    sa.Column('job_lang', sa.String(length=10), nullable=True),
    sa.Column('etl_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('lk_search_history',
    sa.Column('etl_search_id', sa.Integer(), nullable=False),
    sa.Column('search_date', sa.Date(), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('etl_search_id', 'search_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_search_history')
    op.drop_table('lk_jobs')
    op.drop_table('lk_etl_status')
    op.drop_table('lk_companies')
    # ### end Alembic commands ###
