"""adding city on elt config and created at to jobs

Revision ID: 91f4d98615f4
Revises: f0592fc0f887
Create Date: 2025-10-26 13:24:48.203803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f4d98615f4'
down_revision: Union[str, Sequence[str], None] = 'f0592fc0f887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lk_etl_status', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('lk_jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE lk_jobs
        SET created_at = COALESCE(created_at, last_updated, NOW())
    """)

    op.alter_column(
        'lk_jobs',
        'created_at',
        existing_type=sa.DateTime(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_nullable=True
    )

    op.execute("""
        UPDATE lk_etl_status
        SET city = CASE etl_id
            WHEN 1 THEN 'Zurich'
            WHEN 2 THEN 'Basel'
            WHEN 3 THEN 'Geneva'
            WHEN 4 THEN 'Bern'
            ELSE 'Unknown'
        END
    """)

    op.execute("""
        UPDATE lk_etl_status
        SET country = 'Switzerland'
        WHERE country IS NULL OR country = ''
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lk_jobs', 'created_at')
    op.drop_column('lk_etl_status', 'city')
    # ### end Alembic commands ###
