"""adding staging tables for companies and job details

Revision ID: c38c3aa35ceb
Revises: fe5f0f445459
Create Date: 2025-09-17 22:10:34.267325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38c3aa35ceb'
down_revision: Union[str, Sequence[str], None] = 'fe5f0f445459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lk_staging_companies',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_image_url', sa.TEXT(), nullable=True),
    sa.Column('company_description', sa.TEXT(), nullable=True),
    sa.Column('company_staff_count', sa.Integer(), nullable=True),
    sa.Column('company_url', sa.String(length=1000), nullable=True),
    sa.Column('company_follower_count', sa.String(length=255), nullable=True),
    sa.Column('company_industries', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('lk_staging_job_details',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('job_name', sa.String(length=1000), nullable=True),
    sa.Column('standardized_name', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=True),
    sa.Column('job_description', sa.TEXT(), nullable=True),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('job_min_salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('job_max_salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('job_pay_period', sa.String(length=255), nullable=True),
    sa.Column('job_functions', sa.TEXT(), nullable=True),
    sa.Column('job_experience_level', sa.String(length=255), nullable=True),
    sa.Column('job_views', sa.Integer(), nullable=True),
    sa.Column('job_lang', sa.String(length=10), nullable=True),
    sa.Column('etl_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_staging_job_details')
    op.drop_table('lk_staging_companies')
    # ### end Alembic commands ###
