"""removing unused fields for staging table

Revision ID: f0592fc0f887
Revises: c38c3aa35ceb
Create Date: 2025-09-18 20:53:54.818086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0592fc0f887'
down_revision: Union[str, Sequence[str], None] = 'c38c3aa35ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lk_staging_job_details', 'job_lang')
    op.drop_column('lk_staging_job_details', 'etl_id')
    op.drop_column('lk_staging_job_details', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lk_staging_job_details', sa.Column('last_updated', mysql.DATETIME(), nullable=True))
    op.add_column('lk_staging_job_details', sa.Column('etl_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lk_staging_job_details', sa.Column('job_lang', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
