"""adding staging table for job ids

Revision ID: fe5f0f445459
Revises: bd3b8fef2c10
Create Date: 2025-09-12 09:25:39.953330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5f0f445459'
down_revision: Union[str, Sequence[str], None] = 'bd3b8fef2c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lk_staging_jobs',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('etl_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('job_id', 'etl_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_staging_jobs')
    # ### end Alembic commands ###
